name: Continous Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: login to dockerhub
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/website:latest

    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.1.7"
        cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}

    - name: terraform init
      run:
        terraform -chdir=terraform init

    - name: terraform format
      run:
        terraform -chdir=terraform fmt

    - name: terraform validate
      run:
        terraform -chdir=terraform validate

    - name: terraform apply
      run:
        terraform -chdir=terraform apply -auto-approve
